
// Do not edit directly
// Generated on Mon, 15 Jun 2026 07:37:14 GMT

export const mitsubachiTokenTypes = [
"color_primitive_black",
"color_primitive_blue_100",
"color_primitive_blue_110",
"color_primitive_blue_120",
"color_primitive_blue_130",
"color_primitive_blue_140",
"color_primitive_blue_15",
"color_primitive_blue_150",
"color_primitive_blue_160",
"color_primitive_blue_20",
"color_primitive_blue_25",
"color_primitive_blue_30",
"color_primitive_blue_40",
"color_primitive_blue_60",
"color_primitive_blue_65",
"color_primitive_blue_70",
"color_primitive_blue_80",
"color_primitive_brown_100",
"color_primitive_green_100",
"color_primitive_green_120",
"color_primitive_green_15",
"color_primitive_green_150",
"color_primitive_green_65",
"color_primitive_green_80",
"color_primitive_neutral_10",
"color_primitive_neutral_100_alpha",
"color_primitive_neutral_110",
"color_primitive_neutral_120",
"color_primitive_neutral_130",
"color_primitive_neutral_15",
"color_primitive_neutral_160",
"color_primitive_neutral_180",
"color_primitive_neutral_20",
"color_primitive_neutral_20_alpha",
"color_primitive_neutral_200",
"color_primitive_neutral_210",
"color_primitive_neutral_210_alpha",
"color_primitive_neutral_220",
"color_primitive_neutral_230",
"color_primitive_neutral_240",
"color_primitive_neutral_25",
"color_primitive_neutral_25_alpha",
"color_primitive_neutral_30",
"color_primitive_neutral_30_alpha",
"color_primitive_neutral_40_alpha",
"color_primitive_neutral_45",
"color_primitive_neutral_45_alpha",
"color_primitive_neutral_5",
"color_primitive_neutral_5_alpha",
"color_primitive_neutral_50",
"color_primitive_neutral_60",
"color_primitive_neutral_65_alpha",
"color_primitive_neutral_70",
"color_primitive_neutral_90",
"color_primitive_plum_100",
"color_primitive_plum_140",
"color_primitive_red_100",
"color_primitive_red_120",
"color_primitive_red_90",
"color_primitive_tomato_100",
"color_primitive_tomato_120",
"color_primitive_tomato_130",
"color_primitive_tomato_140",
"color_primitive_tomato_15",
"color_primitive_tomato_150",
"color_primitive_tomato_160",
"color_primitive_tomato_20",
"color_primitive_tomato_25",
"color_primitive_tomato_30",
"color_primitive_tomato_60",
"color_primitive_tomato_65",
"color_primitive_tomato_70",
"color_primitive_tomato_80",
"color_primitive_violet_100",
"color_primitive_violet_140",
"color_primitive_viridian_100",
"color_primitive_white",
"color_primitive_white_120_alpha",
"color_primitive_white_20_alpha",
"color_primitive_white_210_alpha",
"color_primitive_white_25_alpha",
"color_primitive_white_30_alpha",
"color_primitive_white_40_alpha",
"color_primitive_white_45_alpha",
"color_primitive_white_65_alpha",
"color_primitive_white_80_alpha",
"color_primitive_yellow_10",
"color_primitive_yellow_140",
"color_primitive_yellow_45",
"color_primitive_yellow_80",
"color_semantic_background_regular",
"color_semantic_background_semi_strong",
"color_semantic_border_danger",
"color_semantic_border_disabled",
"color_semantic_border_error_active",
"color_semantic_border_error_default",
"color_semantic_border_error_hover",
"color_semantic_border_regular",
"color_semantic_border_selected",
"color_semantic_border_semi_strong_active",
"color_semantic_border_semi_strong_default",
"color_semantic_border_semi_strong_hover",
"color_semantic_border_strong",
"color_semantic_elevation_regular",
"color_semantic_elevation_regular_inverse",
"color_semantic_elevation_semi_strong_inverse",
"color_semantic_elevation_semi_weak",
"color_semantic_focus_ring_regular",
"color_semantic_object_danger",
"color_semantic_object_emphasized",
"color_semantic_object_error",
"color_semantic_object_information",
"color_semantic_object_inverse",
"color_semantic_object_link",
"color_semantic_object_negative",
"color_semantic_object_notice",
"color_semantic_object_positive",
"color_semantic_object_regular",
"color_semantic_object_regular_disabled",
"color_semantic_object_selected",
"color_semantic_object_semi_weak_disabled",
"color_semantic_object_static_black",
"color_semantic_object_static_white",
"color_semantic_object_success",
"color_semantic_object_warning",
"color_semantic_object_weak",
"color_semantic_overlay_regular",
"color_semantic_palette_blue",
"color_semantic_palette_brown",
"color_semantic_palette_green",
"color_semantic_palette_neutral",
"color_semantic_palette_plum",
"color_semantic_palette_regular_red",
"color_semantic_palette_semi_strong_red",
"color_semantic_palette_violet",
"color_semantic_palette_viridian",
"color_semantic_surface_checked_active",
"color_semantic_surface_checked_default",
"color_semantic_surface_checked_hover",
"color_semantic_surface_error_active",
"color_semantic_surface_error_default",
"color_semantic_surface_error_hover",
"color_semantic_surface_inactive",
"color_semantic_surface_information",
"color_semantic_surface_negative",
"color_semantic_surface_overlay_active",
"color_semantic_surface_overlay_current_default",
"color_semantic_surface_overlay_current_hover",
"color_semantic_surface_overlay_hover",
"color_semantic_surface_positive",
"color_semantic_surface_regular_active",
"color_semantic_surface_regular_danger_active",
"color_semantic_surface_regular_danger_default",
"color_semantic_surface_regular_danger_hover",
"color_semantic_surface_regular_default",
"color_semantic_surface_regular_disabled",
"color_semantic_surface_regular_hover",
"color_semantic_surface_required",
"color_semantic_surface_selected_active",
"color_semantic_surface_selected_default",
"color_semantic_surface_selected_hover",
"color_semantic_surface_semi_strong_active",
"color_semantic_surface_semi_strong_default",
"color_semantic_surface_semi_strong_disabled",
"color_semantic_surface_semi_strong_hover",
"color_semantic_surface_semi_weak_danger_active",
"color_semantic_surface_semi_weak_danger_hover",
"color_semantic_surface_strong_active",
"color_semantic_surface_strong_default",
"color_semantic_surface_strong_disabled",
"color_semantic_surface_strong_hover",
"color_semantic_surface_success",
"color_semantic_surface_switch_unchecked_active",
"color_semantic_surface_switch_unchecked_default",
"color_semantic_surface_switch_unchecked_hover",
"color_semantic_surface_warning",
"color_semantic_text_danger",
"color_semantic_text_disabled",
"color_semantic_text_error",
"color_semantic_text_inactive",
"color_semantic_text_information",
"color_semantic_text_inverse",
"color_semantic_text_link",
"color_semantic_text_negative",
"color_semantic_text_positive",
"color_semantic_text_regular",
"color_semantic_text_required",
"color_semantic_text_selected",
"color_semantic_text_static_white",
"color_semantic_text_weak",
"color_semantic_zabuton_regular",
"color_semantic_zabuton_semi_strong",
"font_family_ja",
"font_family_zh",
] as const;
export type MitsubachiTokenTypes = (typeof mitsubachiTokenTypes)[number];

export const tokens: {[key in MitsubachiTokenTypes]:string} = {
color_primitive_black: "#000000",
color_primitive_blue_100: "#3f69f2",
color_primitive_blue_110: "#3663f0",
color_primitive_blue_120: "#315ce8",
color_primitive_blue_130: "#214dde",
color_primitive_blue_140: "#143dd0",
color_primitive_blue_15: "#edf1ff",
color_primitive_blue_150: "#0024a0",
color_primitive_blue_160: "#001c78",
color_primitive_blue_20: "#e8edff",
color_primitive_blue_25: "#dbe4ff",
color_primitive_blue_30: "#d5dfff",
color_primitive_blue_40: "#c1d1ff",
color_primitive_blue_60: "#8ea8fb",
color_primitive_blue_65: "#86a2fc",
color_primitive_blue_70: "#7796fc",
color_primitive_blue_80: "#6388ff",
color_primitive_brown_100: "#ae6022",
color_primitive_green_100: "#008744",
color_primitive_green_120: "#00783c",
color_primitive_green_15: "#dff5ea",
color_primitive_green_150: "#004020",
color_primitive_green_65: "#0fbd66",
color_primitive_green_80: "#12a35b",
color_primitive_neutral_10: "#f5f5f5",
color_primitive_neutral_100_alpha: "#0000008a",
color_primitive_neutral_110: "#6f6f6f",
color_primitive_neutral_120: "#686868",
color_primitive_neutral_130: "#5b5b5b",
color_primitive_neutral_15: "#f2f2f2",
color_primitive_neutral_160: "#454545",
color_primitive_neutral_180: "#363636",
color_primitive_neutral_20: "#ededed",
color_primitive_neutral_20_alpha: "#00000012",
color_primitive_neutral_200: "#2d2d2d",
color_primitive_neutral_210: "#282828",
color_primitive_neutral_210_alpha: "#000000d6",
color_primitive_neutral_220: "#222222",
color_primitive_neutral_230: "#1d1d1d",
color_primitive_neutral_240: "#191919",
color_primitive_neutral_25: "#e5e5e5",
color_primitive_neutral_25_alpha: "#0000001a",
color_primitive_neutral_30: "#dfdfdf",
color_primitive_neutral_30_alpha: "#00000021",
color_primitive_neutral_40_alpha: "#0000002e",
color_primitive_neutral_45: "#cbcbcb",
color_primitive_neutral_45_alpha: "#00000033",
color_primitive_neutral_5: "#f8f8f8",
color_primitive_neutral_5_alpha: "#00000008",
color_primitive_neutral_50: "#b6b6b6",
color_primitive_neutral_60: "#acacac",
color_primitive_neutral_65_alpha: "#00000059",
color_primitive_neutral_70: "#9b9b9b",
color_primitive_neutral_90: "#818181",
color_primitive_plum_100: "#c32ec4",
color_primitive_plum_140: "#910091",
color_primitive_red_100: "#e6103d",
color_primitive_red_120: "#d30030",
color_primitive_red_90: "#f72a48",
color_primitive_tomato_100: "#db351f",
color_primitive_tomato_120: "#c92812",
color_primitive_tomato_130: "#b02412",
color_primitive_tomato_140: "#992111",
color_primitive_tomato_15: "#ffedeb",
color_primitive_tomato_150: "#6e160b",
color_primitive_tomato_160: "#520e05",
color_primitive_tomato_20: "#ffebe8",
color_primitive_tomato_25: "#ffdfdb",
color_primitive_tomato_30: "#ffd6d1",
color_primitive_tomato_60: "#ff8a7a",
color_primitive_tomato_65: "#ff7f6e",
color_primitive_tomato_70: "#fc6e5b",
color_primitive_tomato_80: "#f25b44",
color_primitive_violet_100: "#6759ff",
color_primitive_violet_140: "#3e31d5",
color_primitive_viridian_100: "#0d8282",
color_primitive_white: "#ffffff",
color_primitive_white_120_alpha: "#ffffff96",
color_primitive_white_20_alpha: "#ffffff12",
color_primitive_white_210_alpha: "#ffffffd6",
color_primitive_white_25_alpha: "#ffffff1a",
color_primitive_white_30_alpha: "#ffffff21",
color_primitive_white_40_alpha: "#ffffff2e",
color_primitive_white_45_alpha: "#ffffff33",
color_primitive_white_65_alpha: "#ffffff59",
color_primitive_white_80_alpha: "#ffffff73",
color_primitive_yellow_10: "#fcf6d4",
color_primitive_yellow_140: "#5f4f00",
color_primitive_yellow_45: "#f0c800",
color_primitive_yellow_80: "#a98c00",
color_semantic_background_regular: "#ffffff",
color_semantic_background_semi_strong: "#f8f8f8",
color_semantic_border_danger: "#db351f",
color_semantic_border_disabled: "#00000012",
color_semantic_border_error_active: "#6e160b",
color_semantic_border_error_default: "#db351f",
color_semantic_border_error_hover: "#b02412",
color_semantic_border_regular: "#0000001a",
color_semantic_border_selected: "#3f69f2",
color_semantic_border_semi_strong_active: "#0000008a",
color_semantic_border_semi_strong_default: "#00000033",
color_semantic_border_semi_strong_hover: "#00000059",
color_semantic_border_strong: "#000000d6",
color_semantic_elevation_regular: "#00000021",
color_semantic_elevation_regular_inverse: "#ffffff00",
color_semantic_elevation_semi_strong_inverse: "#ffffff00",
color_semantic_elevation_semi_weak: "#0000001a",
color_semantic_focus_ring_regular: "#191919",
color_semantic_object_danger: "#c92812",
color_semantic_object_emphasized: "#315ce8",
color_semantic_object_error: "#c92812",
color_semantic_object_information: "#315ce8",
color_semantic_object_inverse: "#ffffff",
color_semantic_object_link: "#315ce8",
color_semantic_object_negative: "#c92812",
color_semantic_object_notice: "#db351f",
color_semantic_object_positive: "#00783c",
color_semantic_object_regular: "#000000d6",
color_semantic_object_regular_disabled: "#00000059",
color_semantic_object_selected: "#315ce8",
color_semantic_object_semi_weak_disabled: "#0000001a",
color_semantic_object_static_black: "#191919",
color_semantic_object_static_white: "#ffffff",
color_semantic_object_success: "#00783c",
color_semantic_object_warning: "#f0c800",
color_semantic_object_weak: "#0000008a",
color_semantic_overlay_regular: "#00000059",
color_semantic_palette_blue: "#214dde",
color_semantic_palette_brown: "#ae6022",
color_semantic_palette_green: "#008744",
color_semantic_palette_neutral: "#00000033",
color_semantic_palette_plum: "#910091",
color_semantic_palette_regular_red: "#f72a48",
color_semantic_palette_semi_strong_red: "#d30030",
color_semantic_palette_violet: "#3e31d5",
color_semantic_palette_viridian: "#0d8282",
color_semantic_surface_checked_active: "#143dd0",
color_semantic_surface_checked_default: "#3f69f2",
color_semantic_surface_checked_hover: "#315ce8",
color_semantic_surface_error_active: "#ffd6d1",
color_semantic_surface_error_default: "#ffedeb",
color_semantic_surface_error_hover: "#ffdfdb",
color_semantic_surface_inactive: "#00000008",
color_semantic_surface_information: "#edf1ff",
color_semantic_surface_negative: "#ffedeb",
color_semantic_surface_overlay_active: "#0000001a",
color_semantic_surface_overlay_current_default: "#00000012",
color_semantic_surface_overlay_current_hover: "#0000001a",
color_semantic_surface_overlay_hover: "#00000012",
color_semantic_surface_positive: "#dff5ea",
color_semantic_surface_regular_active: "#ededed",
color_semantic_surface_regular_danger_active: "#b02412",
color_semantic_surface_regular_danger_default: "#db351f",
color_semantic_surface_regular_danger_hover: "#c92812",
color_semantic_surface_regular_default: "#ffffff",
color_semantic_surface_regular_disabled: "#00000008",
color_semantic_surface_regular_hover: "#f5f5f5",
color_semantic_surface_required: "#ffedeb",
color_semantic_surface_selected_active: "#d5dfff",
color_semantic_surface_selected_default: "#e8edff",
color_semantic_surface_selected_hover: "#dbe4ff",
color_semantic_surface_semi_strong_active: "#dfdfdf",
color_semantic_surface_semi_strong_default: "#ededed",
color_semantic_surface_semi_strong_disabled: "#00000012",
color_semantic_surface_semi_strong_hover: "#e5e5e5",
color_semantic_surface_semi_weak_danger_active: "#ffebe8",
color_semantic_surface_semi_weak_danger_hover: "#ffedeb",
color_semantic_surface_strong_active: "#000000",
color_semantic_surface_strong_default: "#282828",
color_semantic_surface_strong_disabled: "#0000002e",
color_semantic_surface_strong_hover: "#191919",
color_semantic_surface_success: "#dff5ea",
color_semantic_surface_switch_unchecked_active: "#9b9b9b",
color_semantic_surface_switch_unchecked_default: "#b6b6b6",
color_semantic_surface_switch_unchecked_hover: "#acacac",
color_semantic_surface_warning: "#fcf6d4",
color_semantic_text_danger: "#c92812",
color_semantic_text_disabled: "#00000059",
color_semantic_text_error: "#c92812",
color_semantic_text_inactive: "#00000059",
color_semantic_text_information: "#315ce8",
color_semantic_text_inverse: "#ffffff",
color_semantic_text_link: "#315ce8",
color_semantic_text_negative: "#c92812",
color_semantic_text_positive: "#00783c",
color_semantic_text_regular: "#000000d6",
color_semantic_text_required: "#c92812",
color_semantic_text_selected: "#315ce8",
color_semantic_text_static_white: "#ffffff",
color_semantic_text_weak: "#0000008a",
color_semantic_zabuton_regular: "#ffffff",
color_semantic_zabuton_semi_strong: "#f8f8f8",
font_family_ja: "Arial, YakuHanJPs, Hiragino Sans, Hiragino Kaku Gothic ProN, Meiryo, Noto Sans JP, sans-serif",
font_family_zh: "Arial, YakuHanJPs, 'PingFang SC', 'Microsoft YaHei', 'PingFang TC', Microsoft JhengHei, sans-serif",
}