
// Do not edit directly
// Generated on Wed, 09 Jul 2025 13:24:18 GMT

export const mitsubachiTokenTypes = [
"color_primitive_black",
"color_primitive_blue_10",
"color_primitive_blue_100",
"color_primitive_blue_120",
"color_primitive_blue_130",
"color_primitive_blue_140",
"color_primitive_blue_15",
"color_primitive_blue_150",
"color_primitive_blue_160",
"color_primitive_blue_20",
"color_primitive_blue_25",
"color_primitive_blue_45",
"color_primitive_blue_65",
"color_primitive_blue_70",
"color_primitive_blue_80",
"color_primitive_blue_90",
"color_primitive_green_100",
"color_primitive_green_120",
"color_primitive_green_15",
"color_primitive_green_80",
"color_primitive_neutlra_110_alpha",
"color_primitive_neutlra_140",
"color_primitive_neutlra_140_alpha",
"color_primitive_neutral_10",
"color_primitive_neutral_10_alpha",
"color_primitive_neutral_100",
"color_primitive_neutral_100_alpha",
"color_primitive_neutral_110",
"color_primitive_neutral_120",
"color_primitive_neutral_130",
"color_primitive_neutral_15",
"color_primitive_neutral_15_alpha",
"color_primitive_neutral_150",
"color_primitive_neutral_160",
"color_primitive_neutral_160_alpha",
"color_primitive_neutral_170",
"color_primitive_neutral_170_alpha",
"color_primitive_neutral_20",
"color_primitive_neutral_20_alpha",
"color_primitive_neutral_25",
"color_primitive_neutral_25_alpha",
"color_primitive_neutral_30",
"color_primitive_neutral_30_alpha",
"color_primitive_neutral_40",
"color_primitive_neutral_40_alpha",
"color_primitive_neutral_5",
"color_primitive_neutral_50",
"color_primitive_neutral_50_alpha",
"color_primitive_neutral_60",
"color_primitive_neutral_65",
"color_primitive_neutral_65_alpha",
"color_primitive_neutral_70",
"color_primitive_neutral_90",
"color_primitive_red_10",
"color_primitive_red_100",
"color_primitive_red_120",
"color_primitive_red_15",
"color_primitive_red_25",
"color_primitive_red_5",
"color_primitive_red_90",
"color_primitive_tomato_10",
"color_primitive_tomato_100",
"color_primitive_tomato_120",
"color_primitive_tomato_130",
"color_primitive_tomato_140",
"color_primitive_tomato_15",
"color_primitive_tomato_150",
"color_primitive_tomato_160",
"color_primitive_tomato_170",
"color_primitive_tomato_20",
"color_primitive_tomato_25",
"color_primitive_tomato_70",
"color_primitive_tomato_80",
"color_primitive_tomato_90",
"color_primitive_white",
"color_primitive_yellow_10",
"color_primitive_yellow_45",
"color_semantic_（検証中）overay",
"color_semantic_background_default",
"color_semantic_border_accent_selected",
"color_semantic_border_checked_active",
"color_semantic_border_checked_default",
"color_semantic_border_checked_hover",
"color_semantic_border_danger",
"color_semantic_border_disabled",
"color_semantic_border_error_default",
"color_semantic_border_error_hover",
"color_semantic_border_inverse",
"color_semantic_border_regular_default",
"color_semantic_border_semi_strong_default",
"color_semantic_border_semi_strong_hover",
"color_semantic_border_strong_default",
"color_semantic_chart_heatmap_1",
"color_semantic_chart_heatmap_2",
"color_semantic_chart_heatmap_3",
"color_semantic_chart_heatmap_4",
"color_semantic_focusRing_default",
"color_semantic_highlight_focusRing_default",
"color_semantic_object_accent_selected_default",
"color_semantic_object_danger",
"color_semantic_object_disabled",
"color_semantic_object_error",
"color_semantic_object_flat",
"color_semantic_object_information",
"color_semantic_object_inverse",
"color_semantic_object_link",
"color_semantic_object_negative",
"color_semantic_object_notification",
"color_semantic_object_positive",
"color_semantic_object_regular_default",
"color_semantic_object_semi_weak_default",
"color_semantic_object_success",
"color_semantic_object_warning",
"color_semantic_object_weak_default",
"color_semantic_surface_accent_selected_active",
"color_semantic_surface_accent_selected_default",
"color_semantic_surface_accent_selected_hover",
"color_semantic_surface_button_disabled",
"color_semantic_surface_button_icon_active",
"color_semantic_surface_button_icon_hover",
"color_semantic_surface_button_primary_active",
"color_semantic_surface_button_primary_danger_active",
"color_semantic_surface_button_primary_danger_default",
"color_semantic_surface_button_primary_danger_hover",
"color_semantic_surface_button_primary_default",
"color_semantic_surface_button_primary_hover",
"color_semantic_surface_button_secondary_active",
"color_semantic_surface_button_secondary_danger_active",
"color_semantic_surface_button_secondary_danger_hover",
"color_semantic_surface_button_secondary_hover",
"color_semantic_surface_button_secondary_selected_active",
"color_semantic_surface_button_secondary_selected_default",
"color_semantic_surface_button_secondary_selected_hover",
"color_semantic_surface_button_tertiary_active",
"color_semantic_surface_button_tertiary_danger_active",
"color_semantic_surface_button_tertiary_danger_hover",
"color_semantic_surface_button_tertiary_hover",
"color_semantic_surface_button_text_active",
"color_semantic_surface_button_text_hover",
"color_semantic_surface_checked_active",
"color_semantic_surface_checked_default",
"color_semantic_surface_checked_hover",
"color_semantic_surface_disabled",
"color_semantic_surface_error_active",
"color_semantic_surface_error_default",
"color_semantic_surface_error_hover",
"color_semantic_surface_information",
"color_semantic_surface_overlay",
"color_semantic_surface_regular_active",
"color_semantic_surface_regular_default",
"color_semantic_surface_regular_hover",
"color_semantic_surface_regular_selected_active",
"color_semantic_surface_regular_selected_default",
"color_semantic_surface_regular_selected_hover",
"color_semantic_surface_required_default",
"color_semantic_surface_semi_strong_active",
"color_semantic_surface_semi_strong_default",
"color_semantic_surface_semi_strong_hover",
"color_semantic_surface_semi_strong_selected_active",
"color_semantic_surface_semi_strong_selected_default",
"color_semantic_surface_semi_strong_selected_hover",
"color_semantic_surface_strong_active",
"color_semantic_surface_strong_default",
"color_semantic_surface_strong_hover",
"color_semantic_surface_success",
"color_semantic_surface_tooltips",
"color_semantic_surface_warning",
"color_semantic_text_accent_selected_default",
"color_semantic_text_danger",
"color_semantic_text_disabled",
"color_semantic_text_error",
"color_semantic_text_inverse",
"color_semantic_text_link",
"color_semantic_text_negative",
"color_semantic_text_regular_default",
"color_semantic_text_required",
"color_semantic_text_semi_weak_default",
"color_semantic_text_weak_default",
"color_semantic_zabuton_regular",
"font_family_ja",
"font_family_zh",
] as const;
export type MitsubachiTokenTypes = (typeof mitsubachiTokenTypes)[number];

export const tokens: {[key in MitsubachiTokenTypes]:string} = {
color_primitive_black: "#000000",
color_primitive_blue_10: "#f0f6ff",
color_primitive_blue_100: "#2f73d4",
color_primitive_blue_120: "#2666bf",
color_primitive_blue_130: "#1959b3",
color_primitive_blue_140: "#0a4ba6",
color_primitive_blue_15: "#e8f2ff",
color_primitive_blue_150: "#043478",
color_primitive_blue_160: "#00265c",
color_primitive_blue_20: "#e3efff",
color_primitive_blue_25: "#d4e6ff",
color_primitive_blue_45: "#abceff",
color_primitive_blue_65: "#6ba9ff",
color_primitive_blue_70: "#549bff",
color_primitive_blue_80: "#448df2",
color_primitive_blue_90: "#3980e3",
color_primitive_green_100: "#008744",
color_primitive_green_120: "#00783c",
color_primitive_green_15: "#dff5ea",
color_primitive_green_80: "#12a35b",
color_primitive_neutlra_110_alpha: "#0000008f",
color_primitive_neutlra_140: "#515151",
color_primitive_neutlra_140_alpha: "#000000ad",
color_primitive_neutral_10: "#f5f5f5",
color_primitive_neutral_10_alpha: "#0000000a",
color_primitive_neutral_100: "#757575",
color_primitive_neutral_100_alpha: "#0000008a",
color_primitive_neutral_110: "#6f6f6f",
color_primitive_neutral_120: "#656565",
color_primitive_neutral_130: "#5b5b5b",
color_primitive_neutral_15: "#f2f2f2",
color_primitive_neutral_15_alpha: "#0000000d",
color_primitive_neutral_150: "#363636",
color_primitive_neutral_160: "#282828",
color_primitive_neutral_160_alpha: "#000000d6",
color_primitive_neutral_170: "#191919",
color_primitive_neutral_170_alpha: "#000000e5",
color_primitive_neutral_20: "#ededed",
color_primitive_neutral_20_alpha: "#00000012",
color_primitive_neutral_25: "#e5e5e5",
color_primitive_neutral_25_alpha: "#0000001a",
color_primitive_neutral_30: "#dfdfdf",
color_primitive_neutral_30_alpha: "#00000021",
color_primitive_neutral_40: "#d2d2d2",
color_primitive_neutral_40_alpha: "#0000002e",
color_primitive_neutral_5: "#f8f8f8",
color_primitive_neutral_50: "#b6b6b6",
color_primitive_neutral_50_alpha: "#0000004a",
color_primitive_neutral_60: "#acacac",
color_primitive_neutral_65: "#a5a5a5",
color_primitive_neutral_65_alpha: "#00000059",
color_primitive_neutral_70: "#9b9b9b",
color_primitive_neutral_90: "#818181",
color_primitive_red_10: "#fff3f3",
color_primitive_red_100: "#e6103d",
color_primitive_red_120: "#d30030",
color_primitive_red_15: "#ffebed",
color_primitive_red_25: "#ffddde",
color_primitive_red_5: "#fff6f6",
color_primitive_red_90: "#f72a48",
color_primitive_tomato_10: "#fff4f2",
color_primitive_tomato_100: "#db351f",
color_primitive_tomato_120: "#c92812",
color_primitive_tomato_130: "#b02412",
color_primitive_tomato_140: "#992111",
color_primitive_tomato_15: "#ffedeb",
color_primitive_tomato_150: "#6e160b",
color_primitive_tomato_160: "#520e05",
color_primitive_tomato_170: "#380700",
color_primitive_tomato_20: "#ffebe8",
color_primitive_tomato_25: "#ffdfdb",
color_primitive_tomato_70: "#fc6e5b",
color_primitive_tomato_80: "#f25b44",
color_primitive_tomato_90: "#e8442e",
color_primitive_white: "#ffffff",
color_primitive_yellow_10: "#fcf6d4",
color_primitive_yellow_45: "#f0c800",
color_semantic_（検証中）overay: "#0000004a",
color_semantic_background_default: "#f5f5f5",
color_semantic_border_accent_selected: "#e6103d",
color_semantic_border_checked_active: "#1959b3",
color_semantic_border_checked_default: "#2f73d4",
color_semantic_border_checked_hover: "#2666bf",
color_semantic_border_danger: "#db351f",
color_semantic_border_disabled: "#00000012",
color_semantic_border_error_default: "#db351f",
color_semantic_border_error_hover: "#c92812",
color_semantic_border_inverse: "#ffffff",
color_semantic_border_regular_default: "#00000021",
color_semantic_border_semi_strong_default: "#0000004a",
color_semantic_border_semi_strong_hover: "#0000008f",
color_semantic_border_strong_default: "#000000d6",
color_semantic_chart_heatmap_1: "#6ba9ff",
color_semantic_chart_heatmap_2: "#abceff",
color_semantic_chart_heatmap_3: "#d4e6ff",
color_semantic_chart_heatmap_4: "#e8f2ff",
color_semantic_focusRing_default: "#191919",
color_semantic_highlight_focusRing_default: "#191919",
color_semantic_object_accent_selected_default: "#e6103d",
color_semantic_object_danger: "#db351f",
color_semantic_object_disabled: "#00000059",
color_semantic_object_error: "#db351f",
color_semantic_object_flat: "#9b9b9b",
color_semantic_object_information: "#2f73d4",
color_semantic_object_inverse: "#ffffff",
color_semantic_object_link: "#2666bf",
color_semantic_object_negative: "#db351f",
color_semantic_object_notification: "#e6103d",
color_semantic_object_positive: "#12a35b",
color_semantic_object_regular_default: "#000000d6",
color_semantic_object_semi_weak_default: "#000000ad",
color_semantic_object_success: "#12a35b",
color_semantic_object_warning: "#f0c800",
color_semantic_object_weak_default: "#0000008a",
color_semantic_surface_accent_selected_active: "#ffddde",
color_semantic_surface_accent_selected_default: "#fff3f3",
color_semantic_surface_accent_selected_hover: "#ffebed",
color_semantic_surface_button_disabled: "#0000000d",
color_semantic_surface_button_icon_active: "#00000012",
color_semantic_surface_button_icon_hover: "#0000000a",
color_semantic_surface_button_primary_active: "#000000",
color_semantic_surface_button_primary_danger_active: "#b02412",
color_semantic_surface_button_primary_danger_default: "#db351f",
color_semantic_surface_button_primary_danger_hover: "#c92812",
color_semantic_surface_button_primary_default: "#000000d6",
color_semantic_surface_button_primary_hover: "#000000e5",
color_semantic_surface_button_secondary_active: "#00000012",
color_semantic_surface_button_secondary_danger_active: "#ffedeb",
color_semantic_surface_button_secondary_danger_hover: "#fff4f2",
color_semantic_surface_button_secondary_hover: "#0000000a",
color_semantic_surface_button_secondary_selected_active: "#000000",
color_semantic_surface_button_secondary_selected_default: "#000000d6",
color_semantic_surface_button_secondary_selected_hover: "#000000e5",
color_semantic_surface_button_tertiary_active: "#00000012",
color_semantic_surface_button_tertiary_danger_active: "#ffedeb",
color_semantic_surface_button_tertiary_danger_hover: "#fff4f2",
color_semantic_surface_button_tertiary_hover: "#0000000a",
color_semantic_surface_button_text_active: "#00000012",
color_semantic_surface_button_text_hover: "#0000000a",
color_semantic_surface_checked_active: "#1959b3",
color_semantic_surface_checked_default: "#2f73d4",
color_semantic_surface_checked_hover: "#2666bf",
color_semantic_surface_disabled: "#0000000d",
color_semantic_surface_error_active: "#ffdfdb",
color_semantic_surface_error_default: "#ffedeb",
color_semantic_surface_error_hover: "#ffebe8",
color_semantic_surface_information: "#e8f2ff",
color_semantic_surface_overlay: "#0000004a",
color_semantic_surface_regular_active: "#f2f2f2",
color_semantic_surface_regular_default: "#ffffff",
color_semantic_surface_regular_hover: "#f8f8f8",
color_semantic_surface_regular_selected_active: "#d4e6ff",
color_semantic_surface_regular_selected_default: "#f0f6ff",
color_semantic_surface_regular_selected_hover: "#e3efff",
color_semantic_surface_required_default: "#ffedeb",
color_semantic_surface_semi_strong_active: "#d2d2d2",
color_semantic_surface_semi_strong_default: "#f2f2f2",
color_semantic_surface_semi_strong_hover: "#e5e5e5",
color_semantic_surface_semi_strong_selected_active: "#000000",
color_semantic_surface_semi_strong_selected_default: "#282828",
color_semantic_surface_semi_strong_selected_hover: "#191919",
color_semantic_surface_strong_active: "#9b9b9b",
color_semantic_surface_strong_default: "#b6b6b6",
color_semantic_surface_strong_hover: "#acacac",
color_semantic_surface_success: "#dff5ea",
color_semantic_surface_tooltips: "#000000d6",
color_semantic_surface_warning: "#fcf6d4",
color_semantic_text_accent_selected_default: "#d30030",
color_semantic_text_danger: "#c92812",
color_semantic_text_disabled: "#00000059",
color_semantic_text_error: "#c92812",
color_semantic_text_inverse: "#ffffff",
color_semantic_text_link: "#2666bf",
color_semantic_text_negative: "#c92812",
color_semantic_text_regular_default: "#000000d6",
color_semantic_text_required: "#c92812",
color_semantic_text_semi_weak_default: "#000000ad",
color_semantic_text_weak_default: "#0000008a",
color_semantic_zabuton_regular: "#f8f8f8",
font_family_ja: "Arial, YakuHanJPs, Hiragino Sans, Hiragino Kaku Gothic ProN, Meiryo, Noto Sans JP, sans-serif",
font_family_zh: "Arial, YakuHanJPs, 'PingFang SC', 'Microsoft YaHei', 'PingFang TC', Microsoft JhengHei, sans-serif",
}